### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by chihfanhsu** [SoonyangZhang/rmcat-ns3#1]
Dear authors,

Thanks for the code and great work.

Currently, I want to redo your work. However, when I trying to configure the Webrtc.

I got an error.

I think the error is due to the missing files, such as lrtc_base. However, I cannot find these files.
Can you help me to fix this error?

Many thanks,

Here is the error code
--------------------------------
Checking for library rtc_base
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32mbuild/.conf_check_59a2f4a903af5b095e194cddeff79283/test.cpp[0m

['/usr/bin/g++', '-std=c++11', '-Wall', '-Wno-unused-local-typedefs', '-Wno-deprecated-declarations', '-std=c++11', '-ggdb', '-g3', '-O0', '-D__STDC_CONSTANT_MACROS -DWEBRTC_POSIX -DWEBRTC_LINUX', '-I/home/silver/zsy/webrtc-ns3/webrtc', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '../test.cpp', '-c', '-o', '/home/silver/ns3/ns-3-allinone/ns-3.26/build/.conf_check_59a2f4a903af5b095e194cddeff79283/testbuild/test.cpp.1.o']
[2/2] Linking [33mbuild/.conf_check_59a2f4a903af5b095e194cddeff79283/testbuild/testprog[0m

['/usr/bin/g++', '-lsystem_wrappers', '-lrtc_base', '-lapi', '-llogging', '-lutility', '-lpacing', '-lrtp_rtcp_format', '-L/home/silver/zsy/webrtc-ns3/webrtc/system_wrappers', '-L/home/silver/zsy/webrtc-ns3/webrtc/rtc_base', '-L/home/silver/zsy/webrtc-ns3/webrtc/api', '-L/home/silver/zsy/webrtc-ns3/webrtc/logging', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/utility', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/pacing', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/congestion_controller', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/bitrate_controller', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/remote_bitrate_estimator', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/rtp_rtcp', 'test.cpp.1.o', '-o', '/home/silver/ns3/ns-3-allinone/ns-3.26/build/.conf_check_59a2f4a903af5b095e194cddeff79283/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lrtc_base']
err: /usr/bin/x86_64-linux-gnu-ld: cannot find -lsystem_wrappers
/usr/bin/x86_64-linux-gnu-ld: cannot find -lrtc_base
/usr/bin/x86_64-linux-gnu-ld: cannot find -lapi
/usr/bin/x86_64-linux-gnu-ld: cannot find -llogging
/usr/bin/x86_64-linux-gnu-ld: cannot find -lutility
/usr/bin/x86_64-linux-gnu-ld: cannot find -lpacing
/usr/bin/x86_64-linux-gnu-ld: cannot find -lrtp_rtcp_format
/usr/bin/x86_64-linux-gnu-ld: cannot find -lrtc_base
collect2: error: ld returned 1 exit status

from /home/silver/ns3/ns-3-allinone/ns-3.26/src/webrtc-ns3: Test does not build: Traceback (most recent call last):
  File "/home/silver/ns3/ns-3-allinone/ns-3.26/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Configure.py", line 335, in run_build
    bld.compile()
  File "/home/silver/ns3/ns-3-allinone/ns-3.26/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Build.py", line 185, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1): 
	{task 140119594306128: cxxprogram test.cpp.1.o -> testprog}
['/usr/bin/g++', '-lsystem_wrappers', '-lrtc_base', '-lapi', '-llogging', '-lutility', '-lpacing', '-lrtp_rtcp_format', '-L/home/silver/zsy/webrtc-ns3/webrtc/system_wrappers', '-L/home/silver/zsy/webrtc-ns3/webrtc/rtc_base', '-L/home/silver/zsy/webrtc-ns3/webrtc/api', '-L/home/silver/zsy/webrtc-ns3/webrtc/logging', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/utility', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/pacing', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/congestion_controller', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/bitrate_controller', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/remote_bitrate_estimator', '-L/home/silver/zsy/webrtc-ns3/webrtc/modules/rtp_rtcp', 'test.cpp.1.o', '-o', '/home/silver/ns3/ns-3-allinone/ns-3.26/build/.conf_check_59a2f4a903af5b095e194cddeff79283/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lrtc_base']

not found
from /home/silver/ns3/ns-3-allinone/ns-3.26/src/webrtc-ns3: The configuration failed
-------------------------------------

**Comment by SoonyangZhang** [comment]
The external dynamic library should be linked in ns3. This GCC implementation is depended on webrtc code(https://github.com/SoonyangZhang/rmcat-ns3/tree/master/home-zsy-webrtc-ns3/webrtc). So build it first (cmake.  make).  Then the lib of rtc_base will be generated.


add the following environment path to /etc/profile, the path to "home-zsy-webrtc-ns3/webrtc" in my computer is "/home/zsy/webrtc-ns3/webrtc".
Change them all with where you put these files.
```
export LD_LIBRARY_PATH=/home/zsy/webrtc-ns3/webrtc/system_wrappers:/home/zsy/webrtc-ns3/webrtc/rtc_base:/home/zsy/webrtc-ns3/webrtc/api:/home/zsy/webrtc-ns3/webrtc/logging:/home/zsy/webrtc-ns3/webrtc/modules/utility:/home/zsy/webrtc-ns3/webrtc/modules/pacing:/home/zsy/webrtc-ns3/webrtc/modules/congestion_controller:/home/zsy/webrtc-ns3/webrtc/modules/bitrate_controller:/home/zsy/webrtc-ns3/webrtc/modules/remote_bitrate_estimator:/home/zsy/webrtc-ns3/webrtc/modules/rtp_rtcp:$LD_LIBRARY_PATH  
export CPLUS_INCLUDE_PATH=CPLUS_INCLUDE_PATH:/home/zsy/webrtc-ns3/webrtc/:/home/zsy/webrtc-ns3/webrtc/system_wrappers:/home/zsy/webrtc-ns3/webrtc/rtc_base:/home/zsy/webrtc-ns3/webrtc/api:/home/zsy/webrtc-ns3/webrtc/logging:/home/zsy/webrtc-ns3/webrtc/modules/utility:/home/zsy/webrtc-ns3/webrtc/modules/pacing:/home/zsy/webrtc-ns3/webrtc/modules/congestion_controller:/home/zsy/webrtc-ns3/webrtc/modules/bitrate_controller:/home/zsy/webrtc-ns3/webrtc/modules/remote_bitrate_estimator:/home/zsy/webrtc-ns3/webrtc/modules/rtp_rtcp  
```
Did it make myself clear？

**Comment by chihfanhsu** [comment]
For building the webrtc, I used "cmake ./" to make it under the folder ~/zsy/webrtc-ns3/webrtc (in my folder, it is /home/silver/zsy/webrtc-ns3/webrtc/).

But it outputs 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
COMM_LIB
    linked by target "rtc_base" in directory /home/silver/zsy/webrtc-ns3/webrtc/rtc_base

-- Configuring incomplete, errors occurred!
See also "/home/silver/zsy/webrtc-ns3/webrtc/CMakeFiles/CMakeOutput.log".

Am I doing the wrong step?

Sorry for the building question because I am not very familiar with the Linux platform.

**Comment by SoonyangZhang** [comment]
i have updated the readme, please follows the tips. After that, if you encounter any problem, then put it on the issue. Before these tips are right configured, please do not reach me for any problem.&nbsp; Several people have run this code&nbsp;
 
---Original---
